# Generated by Django 4.1.2 on 2023-02-05 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppLoginPremios', '0003_alter_premios_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premios',
            name='user',
        ),
        migrations.CreateModel(
            name='PremiosUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='AppLoginPremios.premios')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
