# Generated by Django 4.1.2 on 2023-02-05 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppLoginPremios', '0004_remove_premios_user_premiosuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='premios',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='premios', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PremiosUser',
        ),
    ]
