# Generated by Django 4.1.2 on 2023-02-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLoginPremios', '0005_premios_user_delete_premiosuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='premios',
            name='existe',
            field=models.BooleanField(default=True),
        ),
    ]
