# Generated by Django 4.1.2 on 2023-02-18 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppLoginPremios', '0006_premios_existe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obrass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreObra', models.CharField(max_length=100)),
                ('facultad', models.IntegerField()),
                ('manifestacion', models.CharField(max_length=100)),
                ('existe', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obras', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
