# Generated by Django 4.1.2 on 2023-02-18 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppLoginPremios', '0007_obrass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrass',
            name='facultad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='obrass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obrass', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='premios',
            name='facultad',
            field=models.CharField(max_length=100),
        ),
    ]
