# Generated by Django 4.1.2 on 2023-02-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLoginPremios', '0008_alter_obrass_facultad_alter_obrass_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('facultad', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=100)),
            ],
        ),
    ]
