# Generated by Django 4.1.2 on 2023-02-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLoginPremios', '0010_jurado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='hora',
            field=models.CharField(max_length=100),
        ),
    ]
