# Generated by Django 4.1.2 on 2023-02-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLoginPremios', '0011_alter_cronograma_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='fecha',
            field=models.CharField(max_length=100),
        ),
    ]
